export const GET_CURRENT_BY_CITY_SUCCESS = 'GET_CURRENT_BY_CITY_SUCCESS';
export const GET_CURRENT_BY_CITY_FAIL = 'GET_CURRENT_BY_CITY_FAIL';
export const GET_CURRENT_BY_GPS_SUCCESS = 'GET_CURRENT_BY_GPS_SUCCESS';
export const GET_CURRENT_BY_GPS_FAIL = 'GET_CURRENT_BY_GPS_FAIL';
export const GET_DAILY_SUCCESS = 'GET_DAILY_SUCCESS';
export const GET_DAILY_FAIL = 'GET_DAILY_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';
